### ISSUE TITLE
Error in operator<< for concave_curve

### ISSUE THREAD

**Issue by fernandeslouro** [eugene-che/pwn_cc#1]
When iterating the rate-burst combination, in line 484 of pwn_cc.hpp, it should be
double burst = ray_it->p.y - ray_it->p.x * ray_it->k;
instead of
double burst = ray_it->p.y - ray_it->p.x / ray_it->k;

**Comment by eugene-che** [comment]
Thanks for the report. Hopefully the problem is fixed.
